name: ‼️ Suggestion
description: Suggest an idea a change or feature addition.
title: "[SUGGESTION] <title>"
labels: [suggestion]
body:
- type: dropdown
    attributes:
      label: Is your feature request related to a problem?
      description: Does this suggestion relate to an issue on the server??
      options:
        - Yes
        - No
  validations:
    required: true
- type: textarea
  attributes:
    label: Please describe.
    description: A clear and concise description of what the problem is.
    placeholder: |
      Ex. I'm always frustrated when ...
  validations:
    required: false
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
- type: textarea
  attributes:
    label: Provide a link to the plugin or reference to your suggestion. (If applicable)
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Notes
    description: Add any other context about the suggestion here.
